import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, OneToMany } from 'typeorm';
import { JournalEntryLineEntity } from './journal-entry-line.entity';

export enum JournalType {
  GENERAL = 'GENERAL',         // สมุดรายวันทั่วไป
  SALES = 'SALES',             // สมุดรายวันขาย
  PURCHASE = 'PURCHASE',       // สมุดรายวันซื้อ
  CASH_RECEIPT = 'CASH_RECEIPT',   // สมุดรายวันรับเงิน
  CASH_PAYMENT = 'CASH_PAYMENT',   // สมุดรายวันจ่ายเงิน
  ADJUSTMENT = 'ADJUSTMENT',   // รายการปรับปรุง
}

export enum JournalStatus {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  CANCELLED = 'CANCELLED',
}

export enum ReferenceType {
  MANUAL = 'MANUAL',
  SALES_INVOICE = 'SALES_INVOICE',
  CREDIT_NOTE = 'CREDIT_NOTE',
  GOODS_RECEIPT = 'GOODS_RECEIPT',
  GR_REVERSE = 'GR_REVERSE',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  PAYMENT_VOUCHER = 'PAYMENT_VOUCHER',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  STOCK_ISSUE = 'STOCK_ISSUE',
}

@Entity('journal_entries')
export class JournalEntryEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ name: 'doc_no', type: 'varchar', length: 30, unique: true })
  docNo: string; // JV-YYYYMM-XXXX

  @Column({ name: 'journal_type', type: 'varchar', length: 20, default: JournalType.GENERAL })
  journalType: JournalType;

  @Column({ name: 'doc_date', type: 'date' })
  docDate: Date;

  @Column({ name: 'posting_date', type: 'date' })
  postingDate: Date;

  @Column({ name: 'period_month', type: 'int' })
  periodMonth: number; // 1-12

  @Column({ name: 'period_year', type: 'int' })
  periodYear: number; // YYYY

  @Column({ type: 'text', nullable: true })
  description: string;

  // Reference to source document
  @Column({ name: 'reference_type', type: 'varchar', length: 30, default: ReferenceType.MANUAL })
  referenceType: ReferenceType;

  @Column({ name: 'reference_id', nullable: true })
  referenceId: number;

  @Column({ name: 'reference_doc_no', type: 'varchar', length: 30, nullable: true })
  referenceDocNo: string;

  // Status
  @Column({ type: 'varchar', length: 20, default: JournalStatus.DRAFT })
  status: JournalStatus;

  // Totals
  @Column({ name: 'total_debit', type: 'decimal', precision: 15, scale: 4, default: 0 })
  totalDebit: number;

  @Column({ name: 'total_credit', type: 'decimal', precision: 15, scale: 4, default: 0 })
  totalCredit: number;

  // Auto-generated flag
  @Column({ name: 'is_auto_generated', type: 'boolean', default: false })
  isAutoGenerated: boolean;

  // Reversing entry
  @Column({ name: 'is_reversing', type: 'boolean', default: false })
  isReversing: boolean;

  @Column({ name: 'reversed_from_id', nullable: true })
  reversedFromId: number;

  @Column({ name: 'reversed_by_id', nullable: true })
  reversedById: number;

  // Posting info
  @Column({ name: 'posted_at', type: 'timestamptz', nullable: true })
  postedAt: Date;

  @Column({ name: 'posted_by', nullable: true })
  postedBy: number;

  // Cancellation
  @Column({ name: 'cancelled_at', type: 'timestamptz', nullable: true })
  cancelledAt: Date;

  @Column({ name: 'cancelled_by', nullable: true })
  cancelledBy: number;

  @Column({ name: 'cancel_reason', type: 'text', nullable: true })
  cancelReason: string;

  // Audit
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;

  @Column({ name: 'created_by', nullable: true })
  createdBy: number;

  @Column({ name: 'updated_by', nullable: true })
  updatedBy: number;

  // Relations
  @OneToMany(() => JournalEntryLineEntity, line => line.journalEntry, { cascade: true })
  lines: JournalEntryLineEntity[];
}
