import React, { useState, useEffect } from 'react';
import {
  Card, Table, Button, Space, Tag, Modal, Form, Input, Select, DatePicker,
  message, Popconfirm, Typography, Row, Col, Divider, InputNumber, Alert
} from 'antd';
import {
  PlusOutlined, DeleteOutlined, EyeOutlined, CheckOutlined,
  CloseOutlined, UndoOutlined, BookOutlined
} from '@ant-design/icons';
import { journalEntriesApi, chartOfAccountsApi } from '../../services/api';
import dayjs from 'dayjs';

const { Title, Text } = Typography;
const { Option } = Select;

interface JournalEntry {
  id: number;
  docNo: string;
  journalType: string;
  docDate: string;
  postingDate: string;
  description: string;
  referenceType: string;
  referenceDocNo?: string;
  status: string;
  totalDebit: number;
  totalCredit: number;
  isAutoGenerated: boolean;
  lines: JournalEntryLine[];
}

interface JournalEntryLine {
  id?: number;
  lineNo: number;
  accountId: number;
  accountCode: string;
  accountName: string;
  description?: string;
  debitAmount: number;
  creditAmount: number;
  partnerName?: string;
}

interface Account {
  id: number;
  code: string;
  name: string;
}

const JOURNAL_TYPES = [
  { value: 'GENERAL', label: 'สมุดรายวันทั่วไป' },
  { value: 'SALES', label: 'สมุดรายวันขาย' },
  { value: 'PURCHASE', label: 'สมุดรายวันซื้อ' },
  { value: 'CASH_RECEIPT', label: 'สมุดรายวันรับเงิน' },
  { value: 'CASH_PAYMENT', label: 'สมุดรายวันจ่ายเงิน' },
  { value: 'ADJUSTMENT', label: 'รายการปรับปรุง' },
];

const STATUS_CONFIG: Record<string, { label: string; color: string }> = {
  DRAFT: { label: 'ฉบับร่าง', color: 'warning' },
  POSTED: { label: 'บันทึกแล้ว', color: 'success' },
  CANCELLED: { label: 'ยกเลิก', color: 'error' },
};

const JournalEntriesPage: React.FC = () => {
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [loading, setLoading] = useState(true);
  const [modalVisible, setModalVisible] = useState(false);
  const [viewModalVisible, setViewModalVisible] = useState(false);
  const [selectedEntry, setSelectedEntry] = useState<JournalEntry | null>(null);
  const [form] = Form.useForm();
  const [lines, setLines] = useState<any[]>([
    { lineNo: 1, accountId: undefined, description: '', debitAmount: 0, creditAmount: 0 },
    { lineNo: 2, accountId: undefined, description: '', debitAmount: 0, creditAmount: 0 },
  ]);

  const [filters, setFilters] = useState({
    startDate: dayjs().startOf('month').format('YYYY-MM-DD'),
    endDate: dayjs().format('YYYY-MM-DD'),
    status: '',
  });

  useEffect(() => {
    loadData();
  }, [filters]);

  const loadData = async () => {
    try {
      setLoading(true);
      const [entriesRes, accountsRes] = await Promise.all([
        journalEntriesApi.getAll(filters),
        chartOfAccountsApi.getAll(),
      ]);
      setEntries(entriesRes.data);
      setAccounts(accountsRes.data);
    } catch (error) {
      message.error('เกิดข้อผิดพลาดในการโหลดข้อมูล');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenModal = () => {
    form.resetFields();
    form.setFieldsValue({
      docDate: dayjs(),
      journalType: 'GENERAL',
    });
    setLines([
      { lineNo: 1, accountId: undefined, description: '', debitAmount: 0, creditAmount: 0 },
      { lineNo: 2, accountId: undefined, description: '', debitAmount: 0, creditAmount: 0 },
    ]);
    setModalVisible(true);
  };

  const handleView = async (entry: JournalEntry) => {
    try {
      const res = await journalEntriesApi.getById(entry.id);
      setSelectedEntry(res.data);
      setViewModalVisible(true);
    } catch (error) {
      message.error('เกิดข้อผิดพลาด');
    }
  };

  const handleAddLine = () => {
    setLines([...lines, {
      lineNo: lines.length + 1,
      accountId: undefined,
      description: '',
      debitAmount: 0,
      creditAmount: 0,
    }]);
  };

  const handleRemoveLine = (index: number) => {
    if (lines.length <= 2) return;
    const newLines = lines.filter((_, i) => i !== index).map((l, i) => ({ ...l, lineNo: i + 1 }));
    setLines(newLines);
  };

  const handleLineChange = (index: number, field: string, value: any) => {
    const newLines = [...lines];
    newLines[index] = { ...newLines[index], [field]: value };
    setLines(newLines);
  };

  const calculateTotals = () => {
    const totalDebit = lines.reduce((sum, l) => sum + (Number(l.debitAmount) || 0), 0);
    const totalCredit = lines.reduce((sum, l) => sum + (Number(l.creditAmount) || 0), 0);
    return { totalDebit, totalCredit, isBalanced: Math.abs(totalDebit - totalCredit) < 0.01 };
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const { isBalanced } = calculateTotals();
      
      if (!isBalanced) {
        message.error('ยอดเดบิตและเครดิตต้องเท่ากัน');
        return;
      }

      const data = {
        ...values,
        docDate: values.docDate.format('YYYY-MM-DD'),
        lines: lines.filter(l => l.accountId),
      };

      await journalEntriesApi.create(data);
      message.success('สร้างรายการสำเร็จ');
      setModalVisible(false);
      loadData();
    } catch (error: any) {
      message.error(error.response?.data?.message || 'เกิดข้อผิดพลาด');
    }
  };

  const handlePost = async (id: number) => {
    try {
      await journalEntriesApi.post(id);
      message.success('บันทึกสำเร็จ');
      loadData();
    } catch (error: any) {
      message.error(error.response?.data?.message || 'เกิดข้อผิดพลาด');
    }
  };

  const handleCancel = async (id: number) => {
    const reason = window.prompt('ระบุเหตุผลที่ยกเลิก:');
    if (!reason) return;
    try {
      await journalEntriesApi.cancel(id, reason);
      message.success('ยกเลิกสำเร็จ');
      loadData();
    } catch (error: any) {
      message.error(error.response?.data?.message || 'เกิดข้อผิดพลาด');
    }
  };

  const handleReverse = async (id: number) => {
    try {
      await journalEntriesApi.reverse(id);
      message.success('กลับรายการสำเร็จ');
      loadData();
    } catch (error: any) {
      message.error(error.response?.data?.message || 'เกิดข้อผิดพลาด');
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await journalEntriesApi.delete(id);
      message.success('ลบสำเร็จ');
      loadData();
    } catch (error: any) {
      message.error(error.response?.data?.message || 'เกิดข้อผิดพลาด');
    }
  };

  const { totalDebit, totalCredit, isBalanced } = calculateTotals();

  const columns = [
    {
      title: 'เลขที่เอกสาร',
      dataIndex: 'docNo',
      key: 'docNo',
      render: (text: string, record: JournalEntry) => (
        <div>
          <div style={{ fontWeight: 500 }}>{text}</div>
          {record.referenceDocNo && (
            <Text type="secondary" style={{ fontSize: 12 }}>Ref: {record.referenceDocNo}</Text>
          )}
        </div>
      ),
    },
    {
      title: 'วันที่',
      dataIndex: 'docDate',
      key: 'docDate',
      width: 110,
      render: (date: string) => dayjs(date).format('DD/MM/YYYY'),
    },
    {
      title: 'ประเภท',
      dataIndex: 'journalType',
      key: 'journalType',
      width: 150,
      render: (type: string) => {
        const typeInfo = JOURNAL_TYPES.find(t => t.value === type);
        return <Tag>{typeInfo?.label || type}</Tag>;
      },
    },
    {
      title: 'คำอธิบาย',
      dataIndex: 'description',
      key: 'description',
      render: (text: string, record: JournalEntry) => (
        <Space>
          {text}
          {record.isAutoGenerated && <Tag color="blue">Auto</Tag>}
        </Space>
      ),
    },
    {
      title: 'เดบิต',
      dataIndex: 'totalDebit',
      key: 'totalDebit',
      width: 120,
      align: 'right' as const,
      render: (val: number) => Number(val).toLocaleString('th-TH', { minimumFractionDigits: 2 }),
    },
    {
      title: 'เครดิต',
      dataIndex: 'totalCredit',
      key: 'totalCredit',
      width: 120,
      align: 'right' as const,
      render: (val: number) => Number(val).toLocaleString('th-TH', { minimumFractionDigits: 2 }),
    },
    {
      title: 'สถานะ',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => {
        const config = STATUS_CONFIG[status];
        return <Tag color={config?.color}>{config?.label || status}</Tag>;
      },
    },
    {
      title: 'จัดการ',
      key: 'action',
      width: 150,
      render: (_: unknown, record: JournalEntry) => (
        <Space>
          <Button type="text" icon={<EyeOutlined />} onClick={() => handleView(record)} />
          {record.status === 'DRAFT' && (
            <>
              <Popconfirm title="ต้องการบันทึกรายการนี้?" onConfirm={() => handlePost(record.id)}>
                <Button type="text" icon={<CheckOutlined />} style={{ color: 'green' }} />
              </Popconfirm>
              <Popconfirm title="ต้องการลบรายการนี้?" onConfirm={() => handleDelete(record.id)}>
                <Button type="text" danger icon={<DeleteOutlined />} />
              </Popconfirm>
            </>
          )}
          {record.status === 'POSTED' && (
            <>
              <Popconfirm title="ต้องการกลับรายการนี้?" onConfirm={() => handleReverse(record.id)}>
                <Button type="text" icon={<UndoOutlined />} style={{ color: 'orange' }} />
              </Popconfirm>
              <Button type="text" danger icon={<CloseOutlined />} onClick={() => handleCancel(record.id)} />
            </>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <Card>
        <Row justify="space-between" align="middle" style={{ marginBottom: 16 }}>
          <Col>
            <Space>
              <BookOutlined style={{ fontSize: 24 }} />
              <Title level={4} style={{ margin: 0 }}>สมุดรายวัน (Journal Entries)</Title>
            </Space>
          </Col>
          <Col>
            <Button type="primary" icon={<PlusOutlined />} onClick={handleOpenModal}>
              สร้างรายการใหม่
            </Button>
          </Col>
        </Row>

        {/* Filters */}
        <Row gutter={16} style={{ marginBottom: 16 }}>
          <Col span={6}>
            <DatePicker
              placeholder="วันที่เริ่มต้น"
              value={dayjs(filters.startDate)}
              onChange={(date) => setFilters({ ...filters, startDate: date?.format('YYYY-MM-DD') || '' })}
              style={{ width: '100%' }}
            />
          </Col>
          <Col span={6}>
            <DatePicker
              placeholder="วันที่สิ้นสุด"
              value={dayjs(filters.endDate)}
              onChange={(date) => setFilters({ ...filters, endDate: date?.format('YYYY-MM-DD') || '' })}
              style={{ width: '100%' }}
            />
          </Col>
          <Col span={6}>
            <Select
              placeholder="สถานะ"
              value={filters.status || undefined}
              onChange={(value) => setFilters({ ...filters, status: value || '' })}
              style={{ width: '100%' }}
              allowClear
            >
              <Option value="DRAFT">ฉบับร่าง</Option>
              <Option value="POSTED">บันทึกแล้ว</Option>
              <Option value="CANCELLED">ยกเลิก</Option>
            </Select>
          </Col>
        </Row>

        <Table
          columns={columns}
          dataSource={entries}
          rowKey="id"
          loading={loading}
          size="small"
        />
      </Card>

      {/* Create Modal */}
      <Modal
        title="สร้างสมุดรายวัน"
        open={modalVisible}
        onOk={handleSubmit}
        onCancel={() => setModalVisible(false)}
        width={900}
        okText="บันทึก"
        cancelText="ยกเลิก"
      >
        <Form form={form} layout="vertical">
          <Row gutter={16}>
            <Col span={8}>
              <Form.Item name="docDate" label="วันที่" rules={[{ required: true }]}>
                <DatePicker style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="journalType" label="ประเภท" rules={[{ required: true }]}>
                <Select>
                  {JOURNAL_TYPES.map(t => (
                    <Option key={t.value} value={t.value}>{t.label}</Option>
                  ))}
                </Select>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="description" label="คำอธิบาย">
                <Input />
              </Form.Item>
            </Col>
          </Row>
        </Form>

        <Divider>รายการบัญชี</Divider>

        <Table
          dataSource={lines}
          rowKey="lineNo"
          pagination={false}
          size="small"
          columns={[
            {
              title: '#',
              dataIndex: 'lineNo',
              width: 50,
            },
            {
              title: 'บัญชี',
              dataIndex: 'accountId',
              render: (_: unknown, record: any, index: number) => (
                <Select
                  style={{ width: '100%' }}
                  value={record.accountId}
                  onChange={(value) => handleLineChange(index, 'accountId', value)}
                  showSearch
                  optionFilterProp="children"
                  placeholder="เลือกบัญชี"
                >
                  {accounts.map(a => (
                    <Option key={a.id} value={a.id}>{a.code} - {a.name}</Option>
                  ))}
                </Select>
              ),
            },
            {
              title: 'คำอธิบาย',
              dataIndex: 'description',
              width: 150,
              render: (_: unknown, record: any, index: number) => (
                <Input
                  value={record.description}
                  onChange={(e) => handleLineChange(index, 'description', e.target.value)}
                />
              ),
            },
            {
              title: 'เดบิต',
              dataIndex: 'debitAmount',
              width: 120,
              render: (_: unknown, record: any, index: number) => (
                <InputNumber
                  value={record.debitAmount}
                  onChange={(value) => handleLineChange(index, 'debitAmount', value || 0)}
                  style={{ width: '100%' }}
                  min={0}
                  formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
                />
              ),
            },
            {
              title: 'เครดิต',
              dataIndex: 'creditAmount',
              width: 120,
              render: (_: unknown, record: any, index: number) => (
                <InputNumber
                  value={record.creditAmount}
                  onChange={(value) => handleLineChange(index, 'creditAmount', value || 0)}
                  style={{ width: '100%' }}
                  min={0}
                  formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
                />
              ),
            },
            {
              title: '',
              width: 50,
              render: (_: unknown, __: any, index: number) => (
                <Button
                  type="text"
                  danger
                  icon={<DeleteOutlined />}
                  onClick={() => handleRemoveLine(index)}
                  disabled={lines.length <= 2}
                />
              ),
            },
          ]}
          footer={() => (
            <Row justify="space-between">
              <Col>
                <Button type="dashed" icon={<PlusOutlined />} onClick={handleAddLine}>
                  เพิ่มบรรทัด
                </Button>
              </Col>
              <Col>
                <Space size="large">
                  <Text strong style={{ color: isBalanced ? 'green' : 'red' }}>
                    เดบิต: {totalDebit.toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                  </Text>
                  <Text strong style={{ color: isBalanced ? 'green' : 'red' }}>
                    เครดิต: {totalCredit.toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                  </Text>
                </Space>
              </Col>
            </Row>
          )}
        />

        {!isBalanced && (
          <Alert
            type="error"
            message={`ยอดเดบิตและเครดิตไม่เท่ากัน (ต่าง ${Math.abs(totalDebit - totalCredit).toLocaleString('th-TH', { minimumFractionDigits: 2 })})`}
            style={{ marginTop: 16 }}
          />
        )}
      </Modal>

      {/* View Modal */}
      <Modal
        title={`รายละเอียดสมุดรายวัน - ${selectedEntry?.docNo}`}
        open={viewModalVisible}
        onCancel={() => setViewModalVisible(false)}
        footer={null}
        width={800}
      >
        {selectedEntry && (
          <>
            <Row gutter={16} style={{ marginBottom: 16 }}>
              <Col span={8}>
                <Text type="secondary">วันที่เอกสาร</Text>
                <div>{dayjs(selectedEntry.docDate).format('DD/MM/YYYY')}</div>
              </Col>
              <Col span={8}>
                <Text type="secondary">ประเภท</Text>
                <div>{JOURNAL_TYPES.find(t => t.value === selectedEntry.journalType)?.label}</div>
              </Col>
              <Col span={8}>
                <Text type="secondary">สถานะ</Text>
                <div>
                  <Tag color={STATUS_CONFIG[selectedEntry.status]?.color}>
                    {STATUS_CONFIG[selectedEntry.status]?.label}
                  </Tag>
                </div>
              </Col>
              <Col span={24} style={{ marginTop: 8 }}>
                <Text type="secondary">คำอธิบาย</Text>
                <div>{selectedEntry.description || '-'}</div>
              </Col>
            </Row>

            <Table
              dataSource={selectedEntry.lines}
              rowKey="id"
              pagination={false}
              size="small"
              columns={[
                { title: 'รหัสบัญชี', dataIndex: 'accountCode', width: 100 },
                { title: 'ชื่อบัญชี', dataIndex: 'accountName' },
                { title: 'คำอธิบาย', dataIndex: 'description', render: (t: string) => t || '-' },
                {
                  title: 'เดบิต',
                  dataIndex: 'debitAmount',
                  width: 120,
                  align: 'right',
                  render: (val: number) => val > 0 ? Number(val).toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-',
                },
                {
                  title: 'เครดิต',
                  dataIndex: 'creditAmount',
                  width: 120,
                  align: 'right',
                  render: (val: number) => val > 0 ? Number(val).toLocaleString('th-TH', { minimumFractionDigits: 2 }) : '-',
                },
              ]}
              summary={() => (
                <Table.Summary.Row style={{ background: '#fafafa' }}>
                  <Table.Summary.Cell index={0} colSpan={3}>
                    <Text strong>รวม</Text>
                  </Table.Summary.Cell>
                  <Table.Summary.Cell index={1} align="right">
                    <Text strong>{Number(selectedEntry.totalDebit).toLocaleString('th-TH', { minimumFractionDigits: 2 })}</Text>
                  </Table.Summary.Cell>
                  <Table.Summary.Cell index={2} align="right">
                    <Text strong>{Number(selectedEntry.totalCredit).toLocaleString('th-TH', { minimumFractionDigits: 2 })}</Text>
                  </Table.Summary.Cell>
                </Table.Summary.Row>
              )}
            />
          </>
        )}
      </Modal>
    </div>
  );
};

export default JournalEntriesPage;
