import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Paper, Button, Table, TableBody, TableCell,
  TableContainer, TableHead, TableRow, IconButton, Dialog, DialogTitle,
  DialogContent, DialogActions, TextField, Select, MenuItem, FormControl,
  InputLabel, Chip, Alert, Snackbar, Grid, Divider, CircularProgress,
  Card, CardContent
} from '@mui/material';
import {
  Add as AddIcon, Edit as EditIcon, Delete as DeleteIcon,
  Visibility as ViewIcon, Check as PostIcon, Close as CancelIcon,
  Undo as ReverseIcon, Book as JournalIcon
} from '@mui/icons-material';
import { journalEntriesApi, chartOfAccountsApi } from '../../services/api';

interface JournalEntry {
  id: number;
  docNo: string;
  journalType: string;
  docDate: string;
  postingDate: string;
  description: string;
  referenceType: string;
  referenceDocNo?: string;
  status: string;
  totalDebit: number;
  totalCredit: number;
  isAutoGenerated: boolean;
  lines: JournalEntryLine[];
}

interface JournalEntryLine {
  id?: number;
  lineNo: number;
  accountId: number;
  accountCode: string;
  accountName: string;
  description?: string;
  debitAmount: number;
  creditAmount: number;
  partnerName?: string;
}

interface Account {
  id: number;
  code: string;
  name: string;
  accountType: string;
}

const JOURNAL_TYPES = [
  { value: 'GENERAL', label: 'สมุดรายวันทั่วไป' },
  { value: 'SALES', label: 'สมุดรายวันขาย' },
  { value: 'PURCHASE', label: 'สมุดรายวันซื้อ' },
  { value: 'CASH_RECEIPT', label: 'สมุดรายวันรับเงิน' },
  { value: 'CASH_PAYMENT', label: 'สมุดรายวันจ่ายเงิน' },
  { value: 'ADJUSTMENT', label: 'รายการปรับปรุง' },
];

const STATUS_CONFIG: Record<string, { label: string; color: 'default' | 'warning' | 'success' | 'error' }> = {
  DRAFT: { label: 'ฉบับร่าง', color: 'warning' },
  POSTED: { label: 'บันทึกแล้ว', color: 'success' },
  CANCELLED: { label: 'ยกเลิก', color: 'error' },
};

const JournalEntriesPage: React.FC = () => {
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [loading, setLoading] = useState(true);
  const [openDialog, setOpenDialog] = useState(false);
  const [viewDialog, setViewDialog] = useState(false);
  const [selectedEntry, setSelectedEntry] = useState<JournalEntry | null>(null);
  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' as 'success' | 'error' });

  const [filters, setFilters] = useState({
    startDate: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
    status: '',
  });

  const [formData, setFormData] = useState({
    docDate: new Date().toISOString().split('T')[0],
    journalType: 'GENERAL',
    description: '',
    lines: [
      { lineNo: 1, accountId: 0, description: '', debitAmount: 0, creditAmount: 0 },
      { lineNo: 2, accountId: 0, description: '', debitAmount: 0, creditAmount: 0 },
    ] as any[],
  });

  useEffect(() => {
    loadData();
  }, [filters]);

  const loadData = async () => {
    try {
      setLoading(true);
      const [entriesRes, accountsRes] = await Promise.all([
        journalEntriesApi.getAll(filters),
        chartOfAccountsApi.getAll(),
      ]);
      setEntries(entriesRes.data);
      setAccounts(accountsRes.data.filter((a: Account) => a.accountType)); // Filter valid accounts
    } catch (error) {
      console.error('Error loading data:', error);
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาดในการโหลดข้อมูล', severity: 'error' });
    } finally {
      setLoading(false);
    }
  };

  const handleOpenCreate = () => {
    setSelectedEntry(null);
    setFormData({
      docDate: new Date().toISOString().split('T')[0],
      journalType: 'GENERAL',
      description: '',
      lines: [
        { lineNo: 1, accountId: 0, description: '', debitAmount: 0, creditAmount: 0 },
        { lineNo: 2, accountId: 0, description: '', debitAmount: 0, creditAmount: 0 },
      ],
    });
    setOpenDialog(true);
  };

  const handleView = async (entry: JournalEntry) => {
    try {
      const res = await journalEntriesApi.getById(entry.id);
      setSelectedEntry(res.data);
      setViewDialog(true);
    } catch (error) {
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  const handleAddLine = () => {
    setFormData({
      ...formData,
      lines: [...formData.lines, {
        lineNo: formData.lines.length + 1,
        accountId: 0,
        description: '',
        debitAmount: 0,
        creditAmount: 0,
      }],
    });
  };

  const handleRemoveLine = (index: number) => {
    if (formData.lines.length <= 2) return;
    const newLines = formData.lines.filter((_, i) => i !== index).map((l, i) => ({ ...l, lineNo: i + 1 }));
    setFormData({ ...formData, lines: newLines });
  };

  const handleLineChange = (index: number, field: string, value: any) => {
    const newLines = [...formData.lines];
    newLines[index] = { ...newLines[index], [field]: value };
    setFormData({ ...formData, lines: newLines });
  };

  const calculateTotals = () => {
    const totalDebit = formData.lines.reduce((sum, l) => sum + (Number(l.debitAmount) || 0), 0);
    const totalCredit = formData.lines.reduce((sum, l) => sum + (Number(l.creditAmount) || 0), 0);
    return { totalDebit, totalCredit, isBalanced: Math.abs(totalDebit - totalCredit) < 0.01 };
  };

  const handleSubmit = async () => {
    const { isBalanced } = calculateTotals();
    if (!isBalanced) {
      setSnackbar({ open: true, message: 'ยอดเดบิตและเครดิตต้องเท่ากัน', severity: 'error' });
      return;
    }

    try {
      await journalEntriesApi.create(formData);
      setSnackbar({ open: true, message: 'สร้างรายการสำเร็จ', severity: 'success' });
      setOpenDialog(false);
      loadData();
    } catch (error: any) {
      setSnackbar({ open: true, message: error.response?.data?.message || 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  const handlePost = async (id: number) => {
    if (!window.confirm('ต้องการบันทึกรายการนี้?')) return;
    try {
      await journalEntriesApi.post(id);
      setSnackbar({ open: true, message: 'บันทึกสำเร็จ', severity: 'success' });
      loadData();
    } catch (error: any) {
      setSnackbar({ open: true, message: error.response?.data?.message || 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  const handleCancel = async (id: number) => {
    const reason = window.prompt('ระบุเหตุผลที่ยกเลิก:');
    if (!reason) return;
    try {
      await journalEntriesApi.cancel(id, reason);
      setSnackbar({ open: true, message: 'ยกเลิกสำเร็จ', severity: 'success' });
      loadData();
    } catch (error: any) {
      setSnackbar({ open: true, message: error.response?.data?.message || 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  const handleReverse = async (id: number) => {
    if (!window.confirm('ต้องการกลับรายการนี้?')) return;
    try {
      await journalEntriesApi.reverse(id);
      setSnackbar({ open: true, message: 'กลับรายการสำเร็จ', severity: 'success' });
      loadData();
    } catch (error: any) {
      setSnackbar({ open: true, message: error.response?.data?.message || 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm('ต้องการลบรายการนี้?')) return;
    try {
      await journalEntriesApi.delete(id);
      setSnackbar({ open: true, message: 'ลบสำเร็จ', severity: 'success' });
      loadData();
    } catch (error: any) {
      setSnackbar({ open: true, message: error.response?.data?.message || 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  const { totalDebit, totalCredit, isBalanced } = calculateTotals();

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          <JournalIcon sx={{ fontSize: 32, color: 'primary.main' }} />
          <Typography variant="h5" fontWeight="bold">สมุดรายวัน (Journal Entries)</Typography>
        </Box>
        <Button variant="contained" startIcon={<AddIcon />} onClick={handleOpenCreate}>
          สร้างรายการใหม่
        </Button>
      </Box>

      {/* Filters */}
      <Paper sx={{ p: 2, mb: 2 }}>
        <Grid container spacing={2} alignItems="center">
          <Grid item xs={12} sm={3}>
            <TextField
              label="วันที่เริ่มต้น"
              type="date"
              value={filters.startDate}
              onChange={(e) => setFilters({ ...filters, startDate: e.target.value })}
              fullWidth
              size="small"
              InputLabelProps={{ shrink: true }}
            />
          </Grid>
          <Grid item xs={12} sm={3}>
            <TextField
              label="วันที่สิ้นสุด"
              type="date"
              value={filters.endDate}
              onChange={(e) => setFilters({ ...filters, endDate: e.target.value })}
              fullWidth
              size="small"
              InputLabelProps={{ shrink: true }}
            />
          </Grid>
          <Grid item xs={12} sm={3}>
            <FormControl fullWidth size="small">
              <InputLabel>สถานะ</InputLabel>
              <Select
                value={filters.status}
                label="สถานะ"
                onChange={(e) => setFilters({ ...filters, status: e.target.value })}
              >
                <MenuItem value="">ทั้งหมด</MenuItem>
                <MenuItem value="DRAFT">ฉบับร่าง</MenuItem>
                <MenuItem value="POSTED">บันทึกแล้ว</MenuItem>
                <MenuItem value="CANCELLED">ยกเลิก</MenuItem>
              </Select>
            </FormControl>
          </Grid>
        </Grid>
      </Paper>

      {/* Table */}
      <Paper elevation={2}>
        {loading ? (
          <Box sx={{ display: 'flex', justifyContent: 'center', p: 4 }}>
            <CircularProgress />
          </Box>
        ) : (
          <TableContainer>
            <Table size="small">
              <TableHead>
                <TableRow sx={{ bgcolor: 'grey.100' }}>
                  <TableCell>เลขที่เอกสาร</TableCell>
                  <TableCell>วันที่</TableCell>
                  <TableCell>ประเภท</TableCell>
                  <TableCell>คำอธิบาย</TableCell>
                  <TableCell align="right">เดบิต</TableCell>
                  <TableCell align="right">เครดิต</TableCell>
                  <TableCell>สถานะ</TableCell>
                  <TableCell>จัดการ</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {entries.map((entry) => {
                  const statusInfo = STATUS_CONFIG[entry.status] || { label: entry.status, color: 'default' };
                  return (
                    <TableRow key={entry.id} hover>
                      <TableCell>
                        <Typography fontWeight="medium">{entry.docNo}</Typography>
                        {entry.referenceDocNo && (
                          <Typography variant="caption" color="text.secondary">
                            Ref: {entry.referenceDocNo}
                          </Typography>
                        )}
                      </TableCell>
                      <TableCell>{new Date(entry.docDate).toLocaleDateString('th-TH')}</TableCell>
                      <TableCell>
                        <Chip 
                          label={JOURNAL_TYPES.find(t => t.value === entry.journalType)?.label || entry.journalType}
                          size="small"
                          variant="outlined"
                        />
                      </TableCell>
                      <TableCell>
                        {entry.description}
                        {entry.isAutoGenerated && (
                          <Chip label="Auto" size="small" sx={{ ml: 1 }} />
                        )}
                      </TableCell>
                      <TableCell align="right">
                        {Number(entry.totalDebit).toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                      </TableCell>
                      <TableCell align="right">
                        {Number(entry.totalCredit).toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                      </TableCell>
                      <TableCell>
                        <Chip label={statusInfo.label} size="small" color={statusInfo.color} />
                      </TableCell>
                      <TableCell>
                        <IconButton size="small" onClick={() => handleView(entry)}>
                          <ViewIcon />
                        </IconButton>
                        {entry.status === 'DRAFT' && (
                          <>
                            <IconButton size="small" color="success" onClick={() => handlePost(entry.id)}>
                              <PostIcon />
                            </IconButton>
                            <IconButton size="small" color="error" onClick={() => handleDelete(entry.id)}>
                              <DeleteIcon />
                            </IconButton>
                          </>
                        )}
                        {entry.status === 'POSTED' && (
                          <>
                            <IconButton size="small" color="warning" onClick={() => handleReverse(entry.id)}>
                              <ReverseIcon />
                            </IconButton>
                            <IconButton size="small" color="error" onClick={() => handleCancel(entry.id)}>
                              <CancelIcon />
                            </IconButton>
                          </>
                        )}
                      </TableCell>
                    </TableRow>
                  );
                })}
                {entries.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={8} align="center" sx={{ py: 4 }}>
                      <Typography color="text.secondary">ไม่พบรายการ</Typography>
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </Paper>

      {/* Create Dialog */}
      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="lg" fullWidth>
        <DialogTitle>สร้างสมุดรายวัน</DialogTitle>
        <DialogContent dividers>
          <Grid container spacing={2} sx={{ mb: 2 }}>
            <Grid item xs={12} sm={4}>
              <TextField
                label="วันที่"
                type="date"
                value={formData.docDate}
                onChange={(e) => setFormData({ ...formData, docDate: e.target.value })}
                fullWidth
                size="small"
                InputLabelProps={{ shrink: true }}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <FormControl fullWidth size="small">
                <InputLabel>ประเภท</InputLabel>
                <Select
                  value={formData.journalType}
                  label="ประเภท"
                  onChange={(e) => setFormData({ ...formData, journalType: e.target.value })}
                >
                  {JOURNAL_TYPES.map(t => (
                    <MenuItem key={t.value} value={t.value}>{t.label}</MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12}>
              <TextField
                label="คำอธิบาย"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                fullWidth
                size="small"
              />
            </Grid>
          </Grid>

          <Divider sx={{ my: 2 }} />

          <Typography variant="subtitle2" gutterBottom>รายการบัญชี</Typography>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell width="5%">#</TableCell>
                <TableCell width="35%">บัญชี</TableCell>
                <TableCell width="25%">คำอธิบาย</TableCell>
                <TableCell width="15%" align="right">เดบิต</TableCell>
                <TableCell width="15%" align="right">เครดิต</TableCell>
                <TableCell width="5%"></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {formData.lines.map((line, index) => (
                <TableRow key={index}>
                  <TableCell>{line.lineNo}</TableCell>
                  <TableCell>
                    <FormControl fullWidth size="small">
                      <Select
                        value={line.accountId || ''}
                        onChange={(e) => handleLineChange(index, 'accountId', e.target.value)}
                        displayEmpty
                      >
                        <MenuItem value="">-- เลือกบัญชี --</MenuItem>
                        {accounts.map(a => (
                          <MenuItem key={a.id} value={a.id}>
                            {a.code} - {a.name}
                          </MenuItem>
                        ))}
                      </Select>
                    </FormControl>
                  </TableCell>
                  <TableCell>
                    <TextField
                      value={line.description || ''}
                      onChange={(e) => handleLineChange(index, 'description', e.target.value)}
                      fullWidth
                      size="small"
                    />
                  </TableCell>
                  <TableCell>
                    <TextField
                      type="number"
                      value={line.debitAmount || ''}
                      onChange={(e) => handleLineChange(index, 'debitAmount', Number(e.target.value) || 0)}
                      fullWidth
                      size="small"
                      inputProps={{ style: { textAlign: 'right' } }}
                    />
                  </TableCell>
                  <TableCell>
                    <TextField
                      type="number"
                      value={line.creditAmount || ''}
                      onChange={(e) => handleLineChange(index, 'creditAmount', Number(e.target.value) || 0)}
                      fullWidth
                      size="small"
                      inputProps={{ style: { textAlign: 'right' } }}
                    />
                  </TableCell>
                  <TableCell>
                    <IconButton size="small" onClick={() => handleRemoveLine(index)} disabled={formData.lines.length <= 2}>
                      <DeleteIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
              <TableRow>
                <TableCell colSpan={3} align="right">
                  <Button size="small" startIcon={<AddIcon />} onClick={handleAddLine}>
                    เพิ่มบรรทัด
                  </Button>
                </TableCell>
                <TableCell align="right">
                  <Typography fontWeight="bold" color={isBalanced ? 'success.main' : 'error.main'}>
                    {totalDebit.toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                  </Typography>
                </TableCell>
                <TableCell align="right">
                  <Typography fontWeight="bold" color={isBalanced ? 'success.main' : 'error.main'}>
                    {totalCredit.toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                  </Typography>
                </TableCell>
                <TableCell />
              </TableRow>
            </TableBody>
          </Table>

          {!isBalanced && (
            <Alert severity="error" sx={{ mt: 2 }}>
              ยอดเดบิตและเครดิตไม่เท่ากัน (ต่าง {Math.abs(totalDebit - totalCredit).toLocaleString('th-TH', { minimumFractionDigits: 2 })})
            </Alert>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>ยกเลิก</Button>
          <Button variant="contained" onClick={handleSubmit} disabled={!isBalanced}>
            บันทึก
          </Button>
        </DialogActions>
      </Dialog>

      {/* View Dialog */}
      <Dialog open={viewDialog} onClose={() => setViewDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>
          รายละเอียดสมุดรายวัน - {selectedEntry?.docNo}
        </DialogTitle>
        <DialogContent dividers>
          {selectedEntry && (
            <>
              <Grid container spacing={2} sx={{ mb: 2 }}>
                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">วันที่เอกสาร</Typography>
                  <Typography>{new Date(selectedEntry.docDate).toLocaleDateString('th-TH')}</Typography>
                </Grid>
                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">ประเภท</Typography>
                  <Typography>
                    {JOURNAL_TYPES.find(t => t.value === selectedEntry.journalType)?.label}
                  </Typography>
                </Grid>
                <Grid item xs={6} sm={3}>
                  <Typography variant="caption" color="text.secondary">สถานะ</Typography>
                  <Box>
                    <Chip 
                      label={STATUS_CONFIG[selectedEntry.status]?.label} 
                      size="small" 
                      color={STATUS_CONFIG[selectedEntry.status]?.color}
                    />
                  </Box>
                </Grid>
                <Grid item xs={12}>
                  <Typography variant="caption" color="text.secondary">คำอธิบาย</Typography>
                  <Typography>{selectedEntry.description || '-'}</Typography>
                </Grid>
              </Grid>

              <Table size="small">
                <TableHead>
                  <TableRow sx={{ bgcolor: 'grey.100' }}>
                    <TableCell>รหัสบัญชี</TableCell>
                    <TableCell>ชื่อบัญชี</TableCell>
                    <TableCell>คำอธิบาย</TableCell>
                    <TableCell align="right">เดบิต</TableCell>
                    <TableCell align="right">เครดิต</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {selectedEntry.lines?.map((line) => (
                    <TableRow key={line.id}>
                      <TableCell>{line.accountCode}</TableCell>
                      <TableCell>{line.accountName}</TableCell>
                      <TableCell>{line.description || '-'}</TableCell>
                      <TableCell align="right">
                        {Number(line.debitAmount) > 0 
                          ? Number(line.debitAmount).toLocaleString('th-TH', { minimumFractionDigits: 2 }) 
                          : '-'}
                      </TableCell>
                      <TableCell align="right">
                        {Number(line.creditAmount) > 0 
                          ? Number(line.creditAmount).toLocaleString('th-TH', { minimumFractionDigits: 2 }) 
                          : '-'}
                      </TableCell>
                    </TableRow>
                  ))}
                  <TableRow sx={{ bgcolor: 'grey.50' }}>
                    <TableCell colSpan={3} align="right">
                      <Typography fontWeight="bold">รวม</Typography>
                    </TableCell>
                    <TableCell align="right">
                      <Typography fontWeight="bold">
                        {Number(selectedEntry.totalDebit).toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                      </Typography>
                    </TableCell>
                    <TableCell align="right">
                      <Typography fontWeight="bold">
                        {Number(selectedEntry.totalCredit).toLocaleString('th-TH', { minimumFractionDigits: 2 })}
                      </Typography>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setViewDialog(false)}>ปิด</Button>
        </DialogActions>
      </Dialog>

      <Snackbar 
        open={snackbar.open} 
        autoHideDuration={4000} 
        onClose={() => setSnackbar({ ...snackbar, open: false })}
      >
        <Alert severity={snackbar.severity} onClose={() => setSnackbar({ ...snackbar, open: false })}>
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default JournalEntriesPage;
